### ISSUE TITLE
KeyError: 'SiLU is already registered in activation layer'

### ISSUE THREAD

**Issue by goometasoft** [markomih/SplatFields#1]
```
windows-10 , cuda-12.1 , pytorch-2.2

python train.py ^
-s        E:\AI\test\SplatFields ^
-m        E:\AI\test\SplatFields\output ^
--pc_path E:\AI\test\SplatFields\output\point_cloud\iteration_30000\point_cloud.ply ^
--n_views 100  ^
--encoder_type VarTriPlaneEncoder --D 4 --lambda_norm 0.01 --W 128 --pts_samples load ^
--max_num_pts 100000  --load_time_step 0 --composition_rank 0


D:\conda\envs\cuda121\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "E:\SplatFields\train.py", line 18, in <module>
    from gaussian_renderer import render
  File "E:\SplatFields\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "E:\SplatFields\scene\__init__.py", line 18, in <module>
    from scene.deform_model import SplatFieldsModel
  File "E:\SplatFields\scene\deform_model.py", line 3, in <module>
    from utils.time_utils import SplatFields
  File "E:\SplatFields\utils\time_utils.py", line 7, in <module>
    from scene.tripFields import TriPlaneEncoder, VarTriPlaneEncoder, HexPlaneEncoder, VarHexPlaneEncoder, GridEncoder, VarGridEncoder, LaplaceDensity, BellDensity
  File "E:\SplatFields\scene\tripFields.py", line 6, in <module>
    from .time_decoders import TimeVAEDecoder
  File "E:\SplatFields\scene\time_decoders.py", line 6, in <module>
    from mmgen.models.builder import MODULES
  File "E:\SplatFields\mmgen\models\__init__.py", line 2, in <module>
    from .architectures import *  # noqa: F401, F403
  
  File "E:\SplatFields\mmgen\models\architectures\__init__.py", line 7, in <module>
    from .ddpm import DenoisingUnet
  
  File "E:\SplatFields\mmgen\models\architectures\ddpm\__init__.py", line 2, in <module>
    from .denoising import DenoisingUnet
  
  File "E:\SplatFields\mmgen\models\architectures\ddpm\denoising.py", line 12, in <module>
    from .modules import EmbedSequential, TimeEmbedding
  
  File "E:\SplatFields\mmgen\models\architectures\ddpm\modules.py", line 36, in <module>
    class SiLU(nn.Module):
  
  File "D:\conda\envs\cuda121\lib\site-packages\mmcv\utils\registry.py", line 337, in _register
    self._register_module(module=module, module_name=name, force=force)
  
  File "D:\conda\envs\cuda121\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  
  File "D:\conda\envs\cuda121\lib\site-packages\mmcv\utils\registry.py", line 272, in _register_module
    raise KeyError(f'{name} is already registered '

KeyError: 'SiLU is already registered in activation layer'
```

**Comment by markomih** [comment]
Hi @goometasoft,

Thank you for reaching out, and I'm sorry to hear you're encountering issues setting up the environment on your Windows machine. Unfortunately, I don't have experience with development on Windows to provide specific guidance. The code has been tested on Ubuntu 20.04.

Best regards,
Marko

**Comment by DiHubKi** [comment]
same

**Comment by charyang-ai** [comment]
downgrade your torch version?
