### ISSUE TITLE
RUN /run_owlii.sh met issue :   KeyError: 'SiLU is already registered in activation layer'

### ISSUE THREAD

**Issue by charyang-ai** [markomih/SplatFields#8]
root@titan:/gc/SplatFields# CUDA_VISIBLE_DEVICES=7 ./run_owlii.sh
Traceback (most recent call last):
  File "/gc/SplatFields/train.py", line 18, in <module>
    from gaussian_renderer import render
  File "/gc/SplatFields/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/gc/SplatFields/scene/__init__.py", line 18, in <module>
    from scene.deform_model import SplatFieldsModel
  File "/gc/SplatFields/scene/deform_model.py", line 3, in <module>
    from utils.time_utils import SplatFields
  File "/gc/SplatFields/utils/time_utils.py", line 7, in <module>
    from scene.tripFields import TriPlaneEncoder, VarTriPlaneEncoder, HexPlaneEncoder, VarHexPlaneEncoder, GridEncoder, VarGridEncoder, LaplaceDensity, BellDensity
  File "/gc/SplatFields/scene/tripFields.py", line 6, in <module>
    from .time_decoders import TimeVAEDecoder
  File "/gc/SplatFields/scene/time_decoders.py", line 6, in <module>
    from mmgen.models.builder import MODULES
  File "/gc/SplatFields/src/mmgen/mmgen/models/__init__.py", line 2, in <module>
    from .architectures import *  # noqa: F401, F403
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/__init__.py", line 7, in <module>
    from .ddpm import DenoisingUnet
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/__init__.py", line 2, in <module>
    from .denoising import DenoisingUnet
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/denoising.py", line 12, in <module>
    from .modules import EmbedSequential, TimeEmbedding
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/modules.py", line 36, in <module>
    class SiLU(nn.Module):
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/registry.py", line 337, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/registry.py", line 272, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'SiLU is already registered in activation layer'
Traceback (most recent call last):
  File "/gc/SplatFields/render.py", line 13, in <module>
    from scene import Scene, SplatFieldsModel
  File "/gc/SplatFields/scene/__init__.py", line 18, in <module>
    from scene.deform_model import SplatFieldsModel
  File "/gc/SplatFields/scene/deform_model.py", line 3, in <module>
    from utils.time_utils import SplatFields
  File "/gc/SplatFields/utils/time_utils.py", line 7, in <module>
    from scene.tripFields import TriPlaneEncoder, VarTriPlaneEncoder, HexPlaneEncoder, VarHexPlaneEncoder, GridEncoder, VarGridEncoder, LaplaceDensity, BellDensity
  File "/gc/SplatFields/scene/tripFields.py", line 6, in <module>
    from .time_decoders import TimeVAEDecoder
  File "/gc/SplatFields/scene/time_decoders.py", line 6, in <module>
    from mmgen.models.builder import MODULES
  File "/gc/SplatFields/src/mmgen/mmgen/models/__init__.py", line 2, in <module>
    from .architectures import *  # noqa: F401, F403
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/__init__.py", line 7, in <module>
    from .ddpm import DenoisingUnet
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/__init__.py", line 2, in <module>
    from .denoising import DenoisingUnet
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/denoising.py", line 12, in <module>
    from .modules import EmbedSequential, TimeEmbedding
  File "/gc/SplatFields/src/mmgen/mmgen/models/architectures/ddpm/modules.py", line 36, in <module>
    class SiLU(nn.Module):
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/registry.py", line 337, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/utils/registry.py", line 272, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'SiLU is already registered in activation layer'

**Comment by markomih** [comment]
Hi @charyang-ai , It might be due to a small mismatch in the installed package versions. To ensure compatibility, I used Python 3.7.13 with the following package versions:
```bash
python -m pip install mmcv-full==1.6.0 mmengine==0.10.1
python -m pip install -e git+https://github.com/open-mmlab/mmgeneration@f6551e1d6ca24121d1f0a954c3b3ac15de6d302e#egg=mmgen
```
If the problem persists, feel free to share more details about your environment.

Best,
Marko
